package tv.porst.swfretools.parser.actions.as3;

public class AS3Opcodes {

	public static final int NOP = 0x02; //
	public static final int THROW = 0x03; //
	public static final int GETSUPER = 0x04; //
	public static final int SETSUPER = 0x05; //
	public static final int DXNS = 0x06; //
	public static final int DXNSLATE = 0x07; //
	public static final int KILL = 0x08; //
	public static final int LABEL = 0x09; //
	public static final int IFNLT = 0x0C; //
	public static final int IFNLE = 0x0D; //
	public static final int IFNGT = 0x0E; //
	public static final int IFNGE = 0x0F; //
	public static final int JUMP = 0x10; //
	public static final int IFTRUE = 0x11; //
	public static final int IFFALSE = 0x12; //
	public static final int IFEQ = 0x13; //
	public static final int IFNE = 0x14; //
	public static final int IFLT = 0x15; //
	public static final int IFLE = 0x16; //
	public static final int IFGT = 0x17; //
	public static final int IFGE = 0x18; //
	public static final int IFSTRICTEQ = 0x19; //
	public static final int IFSTRICTNE = 0x1A; //
	public static final int LOOKUPSWITCH = 0x1B; //
	public static final int PUSHWITH  = 0x1C; //
	public static final int POPSCOPE = 0x1D; //
	public static final int NEXTNAME = 0x1E; //
	public static final int HASNEXT = 0x1F; //
	public static final int PUSHNULL = 0x20; //
	public static final int PUSHUNDEFINED = 0x21; //
	public static final int NEXTVALUE = 0x23; //
	public static final int PUSHBYTE = 0x24; //
	public static final int PUSHSHORT = 0x25; //
	public static final int PUSHTRUE = 0x26; //
	public static final int PUSHFALSE = 0x27; //
	public static final int PUSHNAN = 0x28; //
	public static final int POP = 0x29; //
	public static final int DUP = 0x2A; //
	public static final int SWAP = 0x2B; //
	public static final int PUSHSTRING = 0x2C; //
	public static final int PUSHINT = 0x2D; //
	public static final int PUSHUINT = 0x2E; //
	public static final int PUSHDOUBLE = 0x2F; //
	public static final int PUSHSCOPE = 0x30; //
	public static final int PUSHNAMESPACE = 0x31; //
	public static final int HASNEXT2 = 0x32; //
	public static final int NEWFUNCTION = 0x40; //
	public static final int CALL = 0x41;
	public static final int CONSTRUCT = 0x42;
	public static final int CALLMETHOD = 0x43;
	public static final int CALLSTATIC = 0x44;
	public static final int CALLSUPER = 0x45;
	public static final int CALLPROPERTY = 0x46;
	public static final int RETURNVOID = 0x47; //
	public static final int RETURNVALUE = 0x48; //
	public static final int CONSTRUCTSUPER = 0x49;
	public static final int CONSTRUCTPROP = 0x4A;
	public static final int CALLPROPLEX = 0x4C;
	public static final int CALLSUPERVOID = 0x4E;
	public static final int CALLPROPVOID = 0x4F;
	public static final int NEWOBJECT = 0x55; //
	public static final int NEWARRAY = 0x56; //
	public static final int NEWACTIVATION = 0x57; //
	public static final int NEWCLASS = 0x58; //
	public static final int GETDESCENDANTS = 0x59; //
	public static final int NEWCATCH = 0x5A; //
	public static final int FINDPROPSTRICT = 0x5D; //
	public static final int FINDPROPERTY = 0x5E; //
	public static final int GETLEX = 0x60; //
	public static final int SETPROPERTY = 0x61; //
	public static final int GETLOCAL = 0x62; //
	public static final int SETLOCAL = 0x63; //
	public static final int GETGLOBALSCOPE = 0x64; //
	public static final int GETSCOPEOBJECT = 0x65; //
	public static final int GETPROPERTY = 0x66; //
	public static final int INITPROPERTY = 0x68; //
	public static final int DELETEPROPERTY = 0x6A; //
	public static final int GETSLOT = 0x6C; //
	public static final int SETSLOT = 0x6D; //
	public static final int GETGLOBALSLOT = 0x6E; //
	public static final int SETGLOBALSLOT = 0x6F; //
	public static final int CONVERTS = 0x70;
	public static final int ESCXELEM = 0x71; //
	public static final int ESCXATTR = 0x72; //
	public static final int CONVERTI = 0x73;
	public static final int CONVERTU = 0x74;
	public static final int CONVERTD = 0x75;
	public static final int CONVERTB = 0x76;
	public static final int CONVERTO = 0x77;
	public static final int CHECKFILTER = 0x78;
	public static final int COERCE = 0x80;
	public static final int COERCEA = 0x82;
	public static final int COERCES = 0x85;
	public static final int ASTYPE = 0x86;
	public static final int ASTYPELATE = 0x87;
	public static final int NEGATE = 0x90; //
	public static final int INCREMENT = 0x91; //
	public static final int INCLOCAL = 0x92; //
	public static final int DECREMENT = 0x93; //
	public static final int DECLOCAL = 0x94; //
	public static final int TYPEOF = 0x95; //
	public static final int NOT = 0x96; //
	public static final int BITNOT = 0x97;
	public static final int ADD = 0xA0;
	public static final int SUBTRACT = 0xA1; //
	public static final int MULTIPLY = 0xA2; //
	public static final int DIVIDE = 0xA3; //
	public static final int MODULO = 0xA4; //
	public static final int LSHIFT = 0xA5; //
	public static final int RSHIFT = 0xA6; //
	public static final int URSHIFT = 0xA7; //
	public static final int BITAND = 0xA8;
	public static final int BITOR = 0xA9;
	public static final int BITXOR = 0xAA;
	public static final int EQUALS = 0xAB; //
	public static final int STRICTEQUALS = 0xAC; //
	public static final int LESSTHAN = 0xAD; //
	public static final int LESSEQUALS = 0xAE; //
	public static final int GREATERTHAN = 0xAF;
	public static final int INSTANCEOF = 0xB1; //
	public static final int ISTYPE = 0xB2; //
	public static final int ISTYPELATE = 0xB3; //
	public static final int IN = 0xB4; //
	public static final int INCREMENTI = 0xC0; //
	public static final int DECREMENTI = 0xC1; //
	public static final int INCLOCALI = 0xC2; //
	public static final int DECLOCALI = 0xC3; //
	public static final int NEGATEI = 0xC4; //
	public static final int ADDI = 0xC5;
	public static final int SUBTRACTI = 0xC6; //
	public static final int MULTIPLYI = 0xC7; //
	public static final int GETLOCAL0 = 0xD0; //
	public static final int GETLOCAL1 = 0xD1; //
	public static final int GETLOCAL2 = 0xD2; //
	public static final int GETLOCAL3 = 0xD3; //
	public static final int SETLOCAL0 = 0xD4; //
	public static final int SETLOCAL1 = 0xD5; //
	public static final int SETLOCAL2 = 0xD6; //
	public static final int SETLOCAL3 = 0xD7; //
	public static final int DEBUG = 0xEF; //
	public static final int DEBUGLINE = 0xF0; //
	public static final int DEBUGFILE = 0xF1; //

}
